name: git clone/checkout
author: David G. Moore, Jr., <david@dgmjr.io>
description: Clones and checks out the specified branch

branding:
  icon: file-plus
  color: green

inputs:
  token:
    type: string
    required: true
  branch:
    type: string
    required: false
    default: main
  repository:
    type: string
    required: true
    default: ${{ github.repository }}
  path:
    type: string
    required: false
    default: .

runs:
  using: composite
  steps:
    - git-checkout-branch
    name: GH Login With Token
    uses: dgmjr-actions/gh-login-with-token@main
    with:
      git-token: ${{ inputs.token }}
    - git-clone
    name: Clone the branch
    run: git clone -b ${{ inputs.branch }} ${{ inputs.path }}
    shell: pwsh
