name: git clone/checkout
author: David G. Moore, Jr., <david@dgmjr.io>
description: Clones and checks out the specified branch

branding:
  icon: git-pull-request
  color: green

inputs:
  token:
    required: true
    description: GitHub Token
  branch:
    required: false
    default: main
    description: Branch to clone
  repository:
    required: true
    default: ${{ github.repository }}
    description: Repository to clone
  path:
    required: false
    default: .
    description: Path to clone to

runs:
  using: composite
  steps:
    - id: git-checkout-branch
      name: GH Login With Token
      uses: dgmjr-actions/gh-login-with-token@main
      with:
        git-token: ${{ inputs.token }}
    - id: git-clone
      name: Clone the branch
      run: |
        if(!(Test-Path -Path "${{ inputs.path }}"))
        {
          $repository = "${{ inputs.repository }}"
          $repository = $repository -like "https://github.com/*" ? "$repository" : "https://github.com/$repository"
          git clone -b ${{ inputs.branch }} "$repository" ${{ inputs.path }}
        }
        else
        {
          Write-Warning -Message "The path '${{ inputs.path }}' already exists; skipping."
        }
      shell: pwsh
